name: portfolio
description: A responsive Flutter portfolio website showcasing projects, skills, and ways to connect with Anand A J.
publish_to: "none" 
version: 1.0.0+1
homepage: https://anand-a-j.github.io/portfolio-flutter/

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  scrollable_positioned_list: ^0.3.8
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  flutter_animate: ^4.5.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
    - family: Denton
      fonts:
        - asset: assets/fonts/DentonTextTest-BoldItalic.otf
          weight: 700
          style: italic